version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "chalk"
        versions: ["5.x", "6.x"]
      - dependency-name: "inquirer"
        versions: ["9.x", "10.x", "11.x", "12.x", "13.x"]
